namespace RocketLunch.domain.enumerations
{

    public enum Category
    {
        restaurants = 0,
        hotdogs = 1,
        japanese = 2,
        afghani = 3,
        african = 4,
        newamerican = 5,
        tradamerican = 6,
        arabian = 7,
        argentine = 8,
        armenian = 9,
        asianfusion = 10,
        australian = 11,
        baguettes = 12,
        bbq = 13,
        basque = 14,
        beergarden = 15,
        bistros = 16,
        british = 17,
        burgers = 18,
        koren = 19,
        mexican = 20,
        mideastern = 21,
        noodles = 22,
        persian = 23,
        pizza = 24,
        potatoes = 25,
        poutineries = 26,
        pubfood = 27,
        sandwiches = 28,
        seafood = 29,
        soulfood = 30,
        soup = 31,
        steak = 32,
        swedish = 33,
        thai = 34,
        vegan = 35,
        vegetarian = 36,
        vietnamese = 37,
        waffles = 69,
    }

}