// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RocketLunch.data;

namespace RocketLunch.data.Migrations
{
    [DbContext(typeof(LunchContext))]
    [Migration("20191217184740_AddZipToUsers")]
    partial class AddZipToUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RocketLunch.data.entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasColumnName("google_id");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<string>("Nopes")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("nopes")
                        .HasDefaultValue("[]");

                    b.Property<string>("PhotoUrl")
                        .HasColumnName("photo_url");

                    b.Property<string>("Zip")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
