---
memory: 1G
disk_quota: 1G
instances: 1
domain: apps.pcfusw1sbx.solutions.corelogic.com
buildpack: dotnet_core_buildpack
stack: cflinuxfs3
services:
  - RocketRedis
  - clvt-config-svr
timeout: 180
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CACHE_NUGET_PACKAGES: false
  PUBLISH_RELEASE_CONFIG: true
  ASPNETCORE_ENVIRONMENT: sbx
applications:
- name: rocketlunch
  host: rocketlunch
  path: ../RocketLunch.Web/bin/Release/netcoreapp3.1/linux-x64/publish/