version: "3"
services:
  db:
    build: .
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
  redis:
    image: redis
    ports:
      - "6379:6379"
